(define-module (guix-home utils)
  #:use-module (guix gexp)
  #:export (home-config-file home-extra-profile-executable-path))

(define-syntax home-config-file
  (syntax-rules ()
    ((_ file-name exps exps* ...)
     (apply mixed-text-file file-name
                      (map (lambda (item)
			     (if (string? item)
				 (string-append item "\n")
				 item))
			   (list exps exps* ...))))))

(define home-extra-profiles-path
  ;; Path where the profiles generated by manifests are stored.
  (string-append (getenv "HOME") "/.guix-extra-profiles/"))

(define-syntax-rule (home-extra-profile-executable-path profile-name package-name)
  (string-append home-extra-profiles-path
                 (symbol->string 'profile-name)
                 "/"
                 (symbol->string 'profile-name)
                 "/bin/"
                 (symbol->string 'package-name)))
